# Generated by Django 5.1.3 on 2025-02-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MangoExport',
            fields=[
                ('variety', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
            ],
        ),
    ]
